// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeaw_gVN0iQwFHyuF8pQ6PbVDmSVQw8AY',
    appId: '1:1049699819506:web:a4b5e3bedc729aab89956b',
    messagingSenderId: '671839887516',
    projectId: 'gazzer-app',
    authDomain: 'gazzer-app.firebaseapp.com',
    storageBucket: 'gazzer-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfxGdnL_KhgbNDY7mFQh-tHHBqIaxisYw',
    appId: '1:671839887516:ios:bcc4b83bd99284ed798d59',
    messagingSenderId: '671839887516',
    projectId: 'gazzer-app',
    storageBucket: 'gazzer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeUvxAgSWFBS5186lnImZC5YP6AHWLeF4',
    appId: '1:671839887516:ios:bcc4b83bd99284ed798d59',
    messagingSenderId: '671839887516',
    projectId: 'gazzer-app',
    storageBucket: 'gazzer-app.appspot.com',
    androidClientId:  '671839887516-4l42p8bd1b3inrmsc2qcb7h22hub47jk.apps.googleusercontent.com',
    iosClientId:  '671839887516-mdar4q19ic4lo5kq756cs25tllmaavs1.apps.googleusercontent.com',
    iosBundleId: 'com.refilex.gazzer.user',
  );
}
